### ISSUE TITLE
any compatible VSLAM framework 

### ISSUE THREAD

**Issue by wonwon0** [nilseuropa/realsense_ros_gazebo#1]
Hi!

Thank you for your work!

I am a novice in computer vision and was wondering if you had implemented your package with any VSLAM algorithms?

If so, would you be able to point me to the package you used, or even publiish the implementation as an example in your repo.

Meanwhile i'm still trying to make things work on my side. Will uptade if something comes out of it!

Thank you

**Comment by nilseuropa** [comment]
Hi,

my intention with this repo was to provide the proper sensor frames and raw sensor data from simulations. You have to know that I have not finished the descriptions and the plugins as I had no time. I am not planning to insert VSLAM algorithms here as for example the T265 has a proprietary visual-inertial odometry running on a Movidius chip, instead it's plugin is relying on p3d with adjustable odometry noise. 

There are many excellent approaches to VSLAM on github already, please take a look at them here https://github.com/topics/visual-odometry.

**Comment by wonwon0** [comment]
Thank you for your answer! Your work is greatly appreciated!
