### ISSUE TITLE
Depth camera weight too high?

### ISSUE THREAD

**Issue by quantumxt** [nilseuropa/realsense_ros_gazebo#4]
The depth camera shouldn't be that heavy (0.5kg) ? Searched online and found that the D435 weights around 72g (0.072kg) instead.

Reference: https://community.intel.com/t5/Items-with-no-label/D435-D415-weight/m-p/499903#M6056

**Comment by nilseuropa** [comment]
Nice catch, thanks. Updated on humble branch.
